import type { Metadata } from 'next'
import { GoogleAnalytics } from '@next/third-parties/google'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/containers/Footer'
import './globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  verification: {
    google: 'XEttN3J1bXetEr8EleSZ7kltJ9Z-Lrtnjx0mlfLUn8I',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Header />
        <div className="pt-10 md:pt-0 overflow-hidden">{children}</div>
        <Footer />
      </body>

      <GoogleAnalytics gaId="G-R92GYW6HRW" />
    </html>
  )
}
